class States:
    about = 'about'
    news = 'news'
    achievments = 'achievments'
    projects = 'projects'
    contacts = 'contacts'
    comments = 'comments'
    profile = 'profile'
    login = 'login'
    register = 'register'
